### ISSUE TITLE
Apex 5.1

### ISSUE THREAD

**Issue by Ora-solution** [jdemovic/apex-input-type-mask#1]
Does it support apex 5.1?

**Comment by jdemovic** [comment]
Hi,
there are used classes for Universal Theme for 18.2.
I can create another version of plugin for 5.1. (source library works with jQuery in 5.1). But I hve no environment with 5.1 yet :/

EDIT: I tested It just in compatibility mode for 5.0 an It works just fine.

regards
J

**Comment by Ora-solution** [comment]
Hello,
Thanks for your quick response. Appreciate your efforts in this regards. Let me try in my project.

Thanks again for very useful plugin. :)

**Comment by jdemovic** [comment]
hi,
I just tried to install it to APEX 5.1 docker version but it is not compatible. there are calls not supported by previous version. For 5.1 there should be created another plugin with by suported methods.
regards
J

**Comment by jdemovic** [comment]
> 
> 
> Hello,
> Thanks for your quick response. Appreciate your efforts in this regards. Let me try in my project.
> 
> Thanks again for very useful plugin. :)

**Comment by jdemovic** [comment]
@Ora-solution 
hi,
I provided new plugin file compatible with APEX 5.1.
regards
J

**Comment by Ora-solution** [comment]
Hi,
Thank you once again for quick response, hope this will useful for others as well.
